//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurant
    {
        public int restaurantId { get; set; }
        public string restaurantName { get; set; }
        public string restaurantCity { get; set; }
        public string restaurantAddress { get; set; }
        public string restaurantCuisineType { get; set; }
        public string restaurantClosingTime { get; set; }
        public string restaurantWebsite { get; set; }
    }
}
